### ISSUE TITLE
moved to a private bitbucket repo? what the!

### ISSUE THREAD

**Issue by mark-buer** [Snapr/javascript-fx#3]
Hello,

We are using javascript-fx in production, and need to fix a few MS Edge bugs.

We do not have a clone of this github repo, we only have the build products.

Unfortunately, the "we've moved" notice was force pushed to this repo (rather than the typically more polite technique of updating the `README.md` and pushing a single commit!). **The bitbucket repos are all private.**

Further, how is one supposed to contribute back fixes??

Please, please, make those bitbucket repos public. Or, please reinstate the code here on github. The code was, after all, licensed under the MPL.

**Comment by jake-nz** [comment]
Apologies. This was caught up in a batch operation with other, private repos.
